services:
  - type: web
    name: ecatepec_dashboard_v2
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.9
